Update manuall-doc-generator.yml

diff --git a/.github/workflows/manuall-doc-generator.yml b/.github/workflows/manuall-doc-generator.yml
--- a/.github/workflows/manuall-doc-generator.yml
+++ b/.github/workflows/manuall-doc-generator.yml
@@ -13,10 +13,15 @@ jobs:
       runs-on: self-hosted
 
       steps:
-        - name: Extract Repository Name
+        - name: Validate Repository
           run: |
-            REPO_NAME=$(basename "${{ github.event.inputs.github_url }}" .git)
-            echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
+             REPO_NAME=$(basename "${{ github.event.inputs.github_url }}" .git)
+
+                if [ "$REPO_NAME" != "central_repo" ]; then
+                  echo "Invalid repository: $REPO_NAME"
+                  exit 1
+                fi
+              echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
       
         - name: Clone Repository
           run: |
